config/routes.rb
Rails.application.routes.draw do
  resources :products

  get 'products'         =>  'static_pages#products'
  get 'about'            => 'static_pages#about'
  get 'contact'          => 'static_pages#contact'
  root                      'static_pages#index'
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @featured_product = Product.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title>Andrew Taylor's App</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap link -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- Link to all the fonts -->
<link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>
<!-- Font Awesome link -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<!-- Links to the rest of the proejct in the assets folder -->
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<body>


<!-- Bootstrap navbar -->
<nav class="navbar mine">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Andrew Taylor</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav mine navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to 'Orders', orders_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

    <div class="row">
      <div class="col-md-12 text-center hero-text">
        <h2>Order Index Page <h2>
        <% @orders.each do |order| %>
        <%= order.id %>
      <div class="row">
        <div class="col-md-12 text-center" id="product-options">
          <button type="button" class="btn btn-danger" >
            <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "orders-options" %>
          </button>
           <button type="button" class="btn btn-primary" >
              <%= link_to 'Show', order, class: "orders-options" %>
          </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">

    </div>
  </div>
<% end %>
<% if (@orders.empty?) %>
      <div class="row">
        <div class="col-md-12 text-center">
               <button type="button" class="btn btn-primary" id="new-product"><%= link_to 'New Order', new_order_path %></button>
        </div>
<% end %>

app/views/orders/new.html.erb
<div class="container-fluid hero-text">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>New Order</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
       <%= render 'form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= link_to 'Back', orders_path %>
    </div>
  </div>

</div>

app/views/orders/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 text-center hero-text">
      <h2>Order Show Page <h2>
          <div class="col-md-12 text-center">
      <p>Product ID:</p>
      <p> <%= @orders %></p>
    </div>
  </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <button type="button" class="btn btn-primary" >
        <%= link_to 'Back', orders_path %>
       </button>
    </div>
  </div>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container-fluid hero-text-products">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Editing Product</h1>
    </div>
  </div>

  <div class="row text-center">
      <%= render 'form' %>
  </div>

  <div class="row text-center">
    <div class="col-md-6">
       <button type="button" class="btn btn-primary" >
           <%= link_to 'Show', @product %>
       </button>
    </div>
    <div class="col-md-6">
      <button type="button" class="btn btn-primary" >
        <%= link_to 'Back', products_path %>
      </button>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Start of loop for the products -->
<div class="container hero-text-products">

<div class="row">
  <div class="col-md-12 text-center">
    <h1>Listing Products</h1>
  </div>
</div>

<% @products.each do |product| %>
  <div class="row text-center">
    <div class="col-md-3">
        <h2>Name</h2>
        <div class="productInfo">
          <%= product.name %>
        </div>
    </div>
    <div class="col-md-3">
        <h2>Description</h2>
        <div class="productInfo">
           <%= product.description %>
        </div>
    </div>
    <div class="col-md-3">
        <h2>Image url</h2>
        <div class="productInfo">
           <%= image_tag(product.image_url, class: "img-responsive") %>
        </div>
    </div>
    <div class="col-md-3">
      <h2> Price </h2>
      <div class="productInfo">
        <%= product.price %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center" id="product-options">
      <button type="button" class="btn btn-primary" >
       <%= link_to 'Show', product, class: "product-options" %>
      </button>

      <button type="button" class="btn btn-warning" >
         <%= link_to 'Edit', edit_product_path(product), class: "product-options" %>
      </button>

      <button type="button" class="btn btn-danger" >
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "product-options" %>
      </button>
    </div>
  </div>
<!-- End of loop for the products -->
    <% if product == @products.last %>
      <div class="row">
        <div class="col-md-12 text-center">
            <button type="button" class="btn btn-primary" id="new-product"><%= link_to 'New Product', new_product_path %></button>
        </div>
    </div>
    <% end %>
<% end %>
    <% if (@products.empty?) %>
      <div class="row">
        <div class="col-md-12 text-center">
            <button type="button" class="btn btn-primary" id="new-product"><%= link_to 'New Product', new_product_path %></button>
        </div>
    <% end %>

</div>

app/views/products/new.html.erb
<div class="container-fluid hero-text">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>New Product</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
       <%= render 'form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= link_to 'Back', products_path %>
    </div>
  </div>

</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid hero-text-products">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Name:</h1>
      <p> <%= @product.name %></p>
    </div>
  </div>
    <div class="row">
     <div class="col-md-12 text-center">
        <h1>Description:</h1>
        <p><%= @product.description %></p>
      </div>
  </div>
    <div class="row">
      <div class="col-md-12 text-center">
       <h1>Image url:</h1>
       <p> <%= @product.image_url %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <h1> Price </h1>
      <%= @product.price %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <button type="button" class="btn btn-primary" >
         <%= link_to 'Edit', edit_product_path(@product) %> |
      </button>
      <button type="button" class="btn btn-primary" >
        <%= link_to 'Back', products_path %>
       </button>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 text-center hero-text">
        <h1 class="">Meet Andrew Taylor</h1>
        <%= image_tag("me.jpg", class: "me img-responsive") %>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
 <section class="contact">
            <div class="container-fluid">
                <div class="row contact-content hero-text">
                    <div class=" col-xs-12 col-sm-6 col-md-6 text-center">
                        <div>
                          <h1 class="text-center">Contact Me!</h1>
                          <p>Call me: <a href="tel:1234">12345678</a></p>
                          <p>Email:<a href="mailto:theador0691@gmail.com">Theador0691@gmail.com</a></p>
                          <%= image_tag("me.jpg", class: "me-contact img-responsive") %>
                        </div>
                    </div>
                    <form>
                        <div class="form-group col-xs-12 col-sm-6 col-md-6 text-center">
                        <h1 class="">Why don't you say hello!</h1>
                            <label for="name">Your Name</label>
                            <br>
                            <input id="name" type="text" placeholder="Your name here." title="Name." class="form-control">
                            <br>

                            <label for="number">Phone Number</label>
                            <br>
                            <input id="number" type="tel" placeholder="Your number here." title="Your number." class="form-control">
                            <br>
                            <label for="email">Email</label>
                            <br>
                            <input id="email" type="email" placeholder="Your email here." required="requierd" title="Your Email." class="form-control">
                            <br>
                            <label for="message-box">Enter a messaage to send</label>
                            <textarea placeholder="Your message here." id="message-box" class="form-control" style="resize:none" cols="60" row="5" required="requierd"></textarea>
                            <br>
                            <p id="visable-comment"></p>
                            <br>
                            <button type="submit" id="submit" class=" btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </section>

app/views/static_pages/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 text-center hero-text">
        <h1 class="">Home Page</h1>
        <a class="btn btn-large btn-success" href="#"><i class="fa fa-home"></i> Sign up today</a>
    </div>
  </div>
</div>

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<%= @featured_product.name %>